version: '2.1'

services:
 web:
  build: ./api
  command: ["/src/start.sh"]
  volumes:
   - ./api:/src
  ports:
   - "8080:8080"
  depends_on:
    db:
      condition: service_healthy
  
 db:
  image: postgres:9.6
  container_name: psg02
  restart: always
  environment:
      POSTGRES_DB: teonite
      POSTGRES_USER: jaro
      POSTGRES_PASSWORD: ramka123
  healthcheck:
    test: ["CMD-SHELL", "pg_isready -U postgres"]
    interval: 10s
    timeout: 10s
    retries: 3 

 frontend:
    build: ./frontend
    command: ["npm", "start"]
    volumes:
      - ./frontend:/app/frontend
      - node-modules:/app/frontend/node_modules
    ports:
      - "3000:3000"

volumes:
   node-modules:
  
