version: '2.1'

services:
 web:
  build: ./api
  command: ["/src/start.sh"]
  ports:
   - "8080:8080"
  depends_on:
    db:
      condition: service_healthy

 db:
  image: postgres:9.6
  container_name: psg01
  restart: always
  environment:
      POSTGRES_DB: teonite
      POSTGRES_USER: jaro
      POSTGRES_PASSWORD: ramka123
  healthcheck:
    test: ["CMD-SHELL", "pg_isready -U postgres"]
    interval: 10s
    timeout: 10s
    retries: 3

 frontend:
    build: ./frontend
    command: ["nginx", "-g", "daemon off;"]
    ports:
      - "3000:3000"

volumes:
   node-modules:
