export const ADD_AUTHOR = 'ADD_AUTHOR';
export const ADD_AUTHOR_AND_STAT='ADD_AUTHOR_AND_STAT';
export const REMOVE_AUTHOR = 'REMOVE_AUTHOR';
export const INIT_REMOVE_AUTHOR = 'INIT_REMOVE_AUTHOR';
export const COPY_ALL = 'COPY_ALL';

export const FETCH_AUTHORS = 'FETCH_AUTHORS';
export const FETCH_AUTHORS_STATUS='FETCH_AUTHORS_STATUS;'
export const FETCH_AUTHORS_SUCCESS='FETCH_AUTHORS_SUCCESS';
export const FETCH_AUTHORS_FAIL='FETCH_AUTHORS_FAIL';

export const FETCH_STATS_STATUS= 'FETCH_STATS_STATUS'
export const FETCH_STATS_SUCESS ='FETCH_AUTHORS_STAT_SUCESS';
export const FETCH_STAT_FAIL = 'FETCH_STAT_FAIL';


export const REMOVE_STATS = 'REMOVE_STATS';
export const ERROR_RESET = 'ERROR_RESET';
export const CLEAR_CHOOSEN = 'CLEAR_CHOOSEN';
export const INIT_CLEAR = 'INIT_CLEAR';
